### PR TITLE
Fix z-fighting on machines with Embeddium

### PR DESCRIPTION
**Pull request by Technici4n**

### CODE REVIEW

**Comment by unilock** [comment]
In case you're not already aware, this PR appears to be needed on 1.20.1, too.

**Comment by ImAK9** [comment]
> In case you're not already aware, this PR appears to be needed on 1.20.1, too.

I second that, pretty please sir

**Comment by Technici4n** [comment]
I forgot, thanks. Will fix that soon (tomorrow probably).

**Comment by Technici4n** [comment]
The backport will be released in a couple of minutes in MI 1.8.3.

**Pull request merged**
