### PR TITLE
Optimized assets.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Lossless compression (oxipng).

### CODE REVIEW

**Comment by Technici4n** [comment]
No, this looks a lot like PR farming - whether it is or not, it just doesn't feel right to me. Please stop PR'ing this to literally every fabric project.

**Comment by RDKRACZ** [comment]
Well, IDK where you see an issue with smaller jar sizes but I must agree that this definitely looks like PR farming and you are not the first person to say this.

>Please stop PR'ing this to literally every fabric project.

Many devs accepted these changes and didn't call them an issue so please let me contribute in a way I'm able to.

Of course I can send you a zip file with these optimized assets so you can commit them by yourself or even do this comression by yourself - the command I used was `oxipng -arvZt8 -o max --strip all --fix`. If you are not interested at least use GitHub bot and let it do this for you - http://imgbot.net/.

Thanks for not closing without any response whatever your intention was.

**Comment by RDKRACZ** [comment]
>PR farming

May I ask a theoretical question? If this PR was coming from a fresh account, with no other PRs would you accept it?

**Comment by Technici4n** [comment]
> May I ask a theoretical question? If this PR was coming from a fresh account, with no other PRs would you accept it?

Not sure, probably not. There are many good reasons not to accept this change (e.g. someone has to check every single assets still loads, and many others).

**Pull request closed without merging**
