### PR TITLE
Small improve of ru translating

### PR DESCRIPTION
**Pull request by Orygeunik**
Fixed some problems like as:
Bord-free text:
image
image
image

Empty recipes image:
image

Broken markup:
image

Changed translate for word "machine".
At past "machine" translated like a "mechanism", in russian it's acceptably translate (it's may mean part of object), but i think more pretty and correct translates as "machine" (like as complex object, not part)

Also in some place rephrase russian text for more harmony and russian norm.
For example in russian in one paragraph not recommended use pronoun  twice in a row preferably alternate. It's a lexical repetition, and it's not very pretty.
As in English, it is not very good to start an answer with the phrase "because" and other

And so small attempt to translate achievements, but some references (easter eggs) very hard to translate, and in this case i saved original text (so my respect for some ref)

And so very-very-very-very (and more) hard...
Are you ready for this?

Changed translate for word "mixer".
At past "mixer" translated like... so it's hard... like as "mixer in bathroom", at now translated like "mixer for components"

>>> Place for brain explosion <<<

:-)

### CODE REVIEW

**Comment by Orygeunik** [comment]
Oh yeah, and added text from discord FAQ about pipes and black/with-list

Line (EN):
https://github.com/AztechMC/Modern-Industrialization/pull/106/files#diff-bbbcd1f8458f3f63fb20109f5f84502e4989db30da7fcfaa6de78bc9c7559e62R29

Lines (RU):
https://github.com/AztechMC/Modern-Industrialization/pull/106/files#diff-6606889d3d48211fdb7d680bac44832e018b5bc81f06f45d254f397d12cc305bR33
https://github.com/AztechMC/Modern-Industrialization/pull/106/files#diff-6606889d3d48211fdb7d680bac44832e018b5bc81f06f45d254f397d12cc305bR38

**Comment by Azercoco** [comment]
All of this seem perfectly fine. I will check with more carefully tomorrow and merge if there is no issue.

**Comment by Orygeunik** [comment]
Added new rows from commit a5864abae41bfc3fd2d43c8d32af80af1b9ea281
into russian translating file

**Comment by Orygeunik** [comment]
Would be grateful if tagged me in discord server (the same nick) for actualize translating, when added some new text

**Comment by Azercoco** [comment]
All of this seems fine. Thank you for the translation.

**Pull request merged**
